sunpy/ablog

- .coveralls.yml
- .gitignore
- .pep8speaks.yml
- .rtd-environment.yml
- .travis.yml
- LICENSE.rst
- MANIFEST.in
- README.rst
- ablog/__init__.py
- ablog/blog.py
- ablog/commands.py
- ablog/post.py
- ablog/start.py
- ablog/templates/postcard2.html
- docs/conf.py
- docs/index.rst
- docs/manual/api.rst
- docs/manual/auto-github-pages-deploys.rst
- docs/manual/posting-and-listing.rst
- docs/release/ablog-v0.3-released.rst
- docs/release/ablog-v0.9-released.rst
- docs/requirements.txt
- readthedocs.yml
- setup.py
Just a PR to update the master repo to the latest version that has all open PRs sent to the old Repo merged in. 
There is a commit (77d827e7a19beaa73b9d2be6a538509a5d1c5021) that might need reverting.
> All Current PRs open to the old repo

- ablog/commands.py
Hi, thanks update ablog and release v0.9.3.
I fix command.
Please check this commit.
ablog serve
-------------
Details:
1. I set website path `ablog_website='../blog'` in conf.py.
2. Execute `ablog serve` .
3. I get `FileNotFoundError _website` .
I found website setting that is `ablog_builddir` ,
but command help said  `ablog_website` is used for website path.
So, I replace `ablog_builddir` to `ablog_website` in ablog_serve().
ablog serve -r
----------------
Details:
1. Execute `ablog serve -r` .
2. Modify source file.
3. I get `Current directory and its parents doesn't contain configuration file` .
I found that when serving site, then current dir change to website.
So, I set -s option to `ablog build`, and keep confdir at find_confdir().
> fix serve command path

- ablog/blog.py
- ablog/post.py
- ablog/start.py
Allows use of ablog in more complex documentation where posts should be
linked. Default behavior is unchanged.
Should adequately fix #21. (Long-term, it may be worth thinking about how ablog documents the config options, but we're not less documented than some of our other options.)
> Define an auto-orphan option

- ablog/post.py
Somewhere along the line, the update directive broke. The last fix led
to update nodes not being properly checked and confusion as to whether
the first paragraph was supposed to be a title or a paragraph.
This fix goes back and returns everything to the documented update
directive behavior, complete with date checking. The update directive
should be easier to update from this.
> Repair update directive

- ablog/post.py
Fixes #47
Per [the docs](https://www.python.org/dev/peps/pep-0479/#examples-of-breakage)
changing it to `return` should be sufficient.
> Change StopIteration to return

- setup.cfg
Might fix
```python
File "/home/circleci/project/venv/lib/python3.6/site-packages/ablog/__init__.py", line 8, in <module>
from .post import (
File "/home/circleci/project/venv/lib/python3.6/site-packages/ablog/post.py", line 16, in <module>
from werkzeug.contrib.atom import AtomFeed
ModuleNotFoundError: No module named 'werkzeug.contrib'
```
> Pin werkzeug to < 1

- .readthedocs.yml
There are many 404 errors ("not found") with links to
https://ablog.readthedocs.org/, e.g. https://ablog.readthedocs.org/blog/
(found under https://ablog.readthedocs.org/blog.html).
This changes the builder on Read The Docs from "html" to "dirhtml" to
generate the expected URLs.
> Use "dirhtml" builder on Read The Docs

- Makefile
It should only `cd` to the parent directory, and remove `testablog`
instead of `test`.
> Fix "test5"

- README.rst
- docs/index.rst
As intersphinx is already added the list when a new ablog project is generated, I don't think we need to explain further.
Relevant to #59 and #18
> Add intersphinx to the extension list

- ablog/commands.py
Hi,
I've noticed that the GitHub URL is hard coded. It prevents pushing to repositories if there are multiple GitHub accounts configured on the same machine, e.g., if `~/.ssh/config` look like this:
```
Host github.com
Hostname github.com
User git
IdentityFile ~/.ssh/main-user/github/id_rsa
IdentitiesOnly yes
Host github.com-other-user-url
Hostname github.com
User git
IdentityFile ~/.ssh/other-user/github/id_rsa
IdentitiesOnly yes
```
The commit/push with custom URL can be invoked as:
```
ablog deploy -g other-user --github-url="git@github.com-other-user-url" -m "..."
```
> Add custom GitHub URL support

- ablog/__init__.py
- docs/conf.py
- docs/index.rst
I noticed in the docs that it recommends manually adding the templates for this theme to the Sphinx templates path. I believe that this is something that could be automated which would simplify the install process for some folks.
With the changes in this PR I was able to remove the manual modification of the templates path from my build. What do you think?
> Automatically add templates path to documentation

- ablog/__init__.py
- ablog/blog.py
- ablog/post.py
- docs/conf.py
- docs/release/ablog-v0.1-released.rst
This PR adds two features:
- Front-matter can now be used to designate blog post metadata. We use a `blogpost: true` flag to designate a page as a "blog post"
- A configuration option to pattern-match filenames that will be treated as blog posts and have their front-matter used as blog post metadata (AKA, so you don't have to put `blogpost: true` for these files
The implementation may still need a bit of work but does this look good to folks in general? If folks are +1 I can add some docs for this
Also, I looked but I couldn't find any tests to add to. Am I missing something?
As one example, I converted one blog post to use front matter instead of the `post` directive:
- [demo page](https://ablog--69.org.readthedocs.build/release/ablog-v0.1-released/)
- [diff in rst …
> frontmatter and blog post matching

- ablog/post.py
Currently, `:ref:` with title is not working.
index.rst
```rst
=========
example
=========
.. postlist::
:list-style: disk
Cross-referencing
---------------------
.. This works well
* :ref:`post1` 
.. This does not work
* :ref:`My first post! <post1>`
```
post1.rst
```rst
.. post:: Oct 5, 2020
:author: me
=======
post1
=======
welcome to my blog!
```
generated index.html (excerpted)
```html
<ul class="simple">
<li><p><a class="reference internal" href="post1/#post1"><span class="std std-ref">post1</span></a></p></li>
<li><p><span class="xref std std-ref">My first post!</span></p></li>
</ul>
```
log
```
Running Sphinx v3.2.1
loading translations [en]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [dirhtml]: targets for 2 source …
```
> Fix missing reference caused by ref with title

- ablog/__init__.py
- ablog/blog.py
- docs/index.rst
- docs/manual/ablog-quick-start.rst
- docs/manual/posting-and-listing.rst
This is a follow-up to #71 and #69 . It does the following:
- Improves the `glob` matching so that you can search recursively, and so that you can provide a list of multiple glob patterns (e.g. if you want to search for two file types)
- Documents the `glob` matching functionality (so folks know that they have another option to putting `blogpost: true` in the front-matter)
- Adds some more documentation around front-matter behavior etc
- Adds some labels and updates some `ref`s
> improving glob matching and documenting it

- ablog/__init__.py
Currently, the `glob` assumes the current working directory is the documents source directory.
This is most certainly not always the case, for example when running sphinx build via tox: https://github.com/executablebooks/sphinx-book-theme/blob/9bc35d25e361a9dace07a470c59003d056dc0671/tox.ini#L38
This PR ensures that `blog_post_pattern` is taken relative to the `app.srcdir`.
> Ensure `blog_post_pattern` are relative to srcdir

- ablog/post.py
- tests/roots/test-build/conf.py
- tests/roots/test-build/post.rst
- tests/test_build.py
Adds test coverage for existing Atom feed generation and then adds some missing feed
metadata to generated feeds: summary and categories.
----
I checked locally, `$ tox -p all` passes successfully.
Fixes #91
> feat(feeds): Add missing Atom entry metadata

- ablog/blog.py
- ablog/post.py
- ablog/start.py
- docs/manual/ablog-configuration-options.rst
- tests/roots/test-build/conf.py
- tests/roots/test-build/post.rst
- tests/test_build.py
Syndication feeds are often used to interact with external services.  [Planet
Venus](http://intertwingly.net/code/venus/docs/index.html), for example, aggregates
multiple feeds into one topical 'Planet Foo' type site.  Various other services consume
syndication feeds to automatically make social media posts when new entries appear in
the feed.  Whether to comply with community standards on a `Planet Foo` type site or to
feed richer data to an external service whose support for Atom elements is limited, such
as [IFTTT's RSS Feed Service](https://ifttt.com/feed), having rich control over feed
entry element values supports many use cases.
This change adds support for such use cases using Jinja2, as it's already a dependency
of Sphinx, string templates in a new project configuration option. …
> feat(feeds): Add entry element template support

- ablog/blog.py
role ``:ref:`blog-drafts` `` produces a wrong URL.
The drafts URL should be `$BLOG_PATH/drafts.html`. but not `$BLOG_PATH/drafts/index.html`.
But I dont known why https://ablog.readthedocs.io/manual/cross-referencing-blog-pages/ works.
> Correct draft URL

- ablog/blog.py
ABlog create `<blog_path>.html` but not `<blog_path>/index.html`.
It is strange that all ```:ref:`blog-*` ``` references point to wrong URLs :'(
> Correct posts URL

- README.rst
- azure-pipelines.yml
- docs/release/ablog-v0.9-released.rst
- setup.cfg
- tox.ini
We have renamed master to main
Fixes https://github.com/sunpy/ablog/issues/101
We were not testing against sphinx master due to other packages pinning the max version.
I suspect it will be broken.
> rename master to main

- docs/manual/forever-draft.rst
Trivial fix to a tiny typo in the example for referencing the blog-drafts page. Thanks for sharing the extension.
> fix documentation typo in blog-drafts

- ablog/commands.py
- docs/manual/ablog-commands.rst
Add an option to use a different deploy branch than master.
The default is still master, so behavior doesn't change for
current users unless they start adding the option.
> Allow using a different branch when deploying

- ablog/post.py
Markdown post with tags field in front-matter has format mismatch.
```
---
tags: ["a", "b"]
---
```
Interpreted as  `["a"` and `"b"]`.
I'm fix it.
This is caused in 
https://github.com/executablebooks/MyST-Parser/blob/885651fc4e25dbac414c20cfe8fe3232ba4e833b/myst_parser/docutils_renderer.py#L823
And `metadata['tags']` store `["a", "b"]` text.
Thank you.
> Fix tags field for myst_parser

- ablog/blog.py
- ablog/start.py
- ablog/templates/postnavy.html
- docs/manual/ablog-configuration-options.rst
For my blog, I prefer to not show the next / previous links. This PR adds a config item to conditionally show them
> optionally show previous / next links on post page

- ablog/blog.py
- ablog/post.py
- ablog/templates/collection.html
- tests/test_postlist.py
It's difficult to get consistent styling between `.. postlist::` and the archive pages. This PR adds classes to each part of a post to help with styling.
There was also a difference between how `.. postlist::` rendered the expand vs the archive pages. The archive now follows `.. postlist::`
> add classes to post elements

- ablog/post.py
Just use string methods to process tags - no need for eval. This eliminates the warning and incorrect parsing of tags for markdown reported in #128.
Fixes #128
> Get rid of eval and fix #128

- ablog/__init__.py
This fixes #133 by ensuring that paths matched by `blog_post_pattern` are represented as posix-path even on windows and thus compatible with Sphinx.
> Normalise path to posix as sphinx expects

- docs/conf.py
This patch fixes the following warning:
```
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
```
See also: https://github.com/sphinx-doc/sphinx/pull/8898
> docs: Fix format of sphinx.ext.extlink for Sphinx 5.x

- Makefile
- ablog/commands.py
- ablog/post.py
- ablog/start.py
- azure-pipelines.yml
- docs/conf.py
- docs/manual/ablog-i18n.rst
- docs/release/ablog-v0.10-released.rst
- setup.py
- tox.ini
Forgot to enable treat warnings as errors and turns out, lots of warnings.
Fixes https://github.com/sunpy/ablog/issues/137 in theory 
Fixes https://github.com/sunpy/ablog/issues/136 in theory
> Fix warnings and update CI

- ablog/post.py
This improves the logic of the conditional check for some page metadata, which seemed to be breaking docutils on newer versions. I think converting to a list will make the behavior more dependable.
- closes #145
> Improve conditional check for author metadata

- ablog/post.py
Fix #154
Restore `or ""` that is deleted in a3a8fb932dae00cd7766bd38554f98947104f37b.
> Fix the error on some empty option value of post directive

- docs/index.rst
This is a very minor PR that just fixes a typo in docs/index.rst, changing "spondered" to the word "sponsored".
Apologies for not opening an issue first! I'm guessing y'all will want this fixed though and if not, closing a one-commit PR won't hurt me :slightly_smiling_face:
> Fix typo in index.rst: spondered -> sponsored

- docs/conf.py
- src/ablog/templates/ablog/languages.html
- src/ablog/templates/ablog/locations.html
- src/ablog/templates/ablog/postcard.html
- src/ablog/templates/ablog/postcard2.html
- src/ablog/templates/languages.html
- src/ablog/templates/locations.html
- src/ablog/templates/postcard.html
- src/ablog/templates/postcard2.html
- src/ablog/templates/postnavy.html
- tox.ini
I merged the base PR and didn't notice the original was pointing at the branch.
Original comment:
This adds a span wrapper to previous and next buttons so that they can be styled with CSS more easily. (e.g. if you want to position them with `flexbox`.
There are many other places that follow this pattern but I didn't change them in order to keep this PR simpler. But for example, a structure like:
```html
<span>
<i ... >
Some text
</span>
```
and I think it'd be better in general to use a pattern like:
```html
<span>
<i ... >
<span>Some text</span>
</span>
```
This way you can apply styling to the inline text independent of the icon.
Original PR: https://github.com/sunpy/ablog/pull/188
> add ablog-sidebar-item to templates I missed

- src/ablog/templates/ablog/postnavy.html
This copies over some of the HTML fixes that were in an old template path that hadn't been ported to the new template path. It also adds two classes to the prev/next spans so they can be selected more easily.
- closes https://github.com/sunpy/ablog/issues/194
> Clean up prev/next HTML templates

- .gitignore
- setup.cfg
- setup.py
- src/ablog/version.py
- tox.ini
> Update version handling to remove use of pkg_resources 

- src/ablog/post.py
Fixes https://github.com/sunpy/ablog/issues/213
The issue is caused by a wrong check on [findall](https://pydoc.dev/docutils/latest/docutils.nodes.Node.html#findall). This method returns an iterator that evaluates to true. It has to be iterated to properly check if there are any nodes in the document that match.
> avoid spurious warning about posts with front-matter and post directive

- roots/test-build/post.rst
- src/ablog/post.py
- src/ablog/tests/test_build.py
Fixes https://github.com/sunpy/ablog/issues/215
Looking at the code, it seems that there is the intention in `ablog.posts.generate_atom_feeds` to order the posts from newer to older. See:
https://github.com/sunpy/ablog/blob/af590e136e713a3cf4c5b527b78a096226abe3d1/src/ablog/post.py#L675
However, later on, posts in `sorted_posts_by_date` are added to the feed with:
https://github.com/sunpy/ablog/blob/af590e136e713a3cf4c5b527b78a096226abe3d1/src/ablog/post.py#L686
The method [add_entry](https://python-feedgen.readthedocs.io/en/latest/api.feed.html#feedgen.feed.FeedGenerator.add_entry) does prepend each post to the feed though (default behaviour), effectively reversing the order of posts a second time.
This PR explicitly sets the order of `add_entry` to not alter the post order set in …
> append posts to atom feed to keep post order from new to old

- src/ablog/blog.py
- src/ablog/post.py
Fixes #19 
Some RSS readers might render the atom feed locally without any further requests to the remote website. This breaks images in the feed as they are sourced from relative links as discussed in issue #19.
This PR fixes this issue by always using a complete URL based on `blog_baseurl` as source of images in the HTML contents of the feed. Blogs without a `baseurl` will continue to use relative paths in their feeds.
> use fully qualified URLs for images in atom feed

- docs/manual/ablog-configuration-options.rst
Document the config option `post_date_format_short` that is used in recent posts.
I wanted to change the date format in the "Recent Posts" sidebar from
```
23 March - ABlog v0.11 released
```
to something like this
```
03-23 - ABlog v0.11 released
```
Looking at the source, the change was simple (in `conf.py`):
```
post_date_format_short = '%m-%d'
```
But there was no mention in the docs. 😲
This PR fixes this. 🙂
Thanks for creating and maintaining ablog! 🖖
> docs: post_date_format_short

- src/ablog/templates/ablog/postcard2.html
- src/ablog/templates/postcard2.html
fa-pencil-square-o is not presented after fa v5
> change fa-pencil-square-o to fa-edit

- src/ablog/__init__.py
- src/ablog/stylesheets/ablog/tagcloud.css
- src/ablog/templates/ablog/tagcloud.html
- src/ablog/templates/tagcloud.html
Add a stylesheet for tagcloud, as it is removed in #144, close #267.
> Add stylesheet for tagcloud

- .gitignore
- Makefile
ablog requires the root path to exist:
```
$ make demo
rm -rf demo
printf "demo\nABlog\nABlog Team\nhttps://ablog.readthedocs.io/" | ablog start
Welcome to the ABlog 0.11.7.dev8+g72e99ac.d20240106 quick start utility.
Please enter values for the following settings (just press Enter to accept a
default value, if one is given in brackets).
Enter the root path for your blog project (path has to exist).
> Root path for your project (path has to exist) [.]: * Please enter a valid path name.
> Root path for your project (path has to exist) [.]: * Please enter a valid path name.
> Root path for your project (path has to exist) [.]: * Please enter a valid path name.
> Root path for your project (path has to exist) [.]: * Please enter a valid path name.
> Root path for your project (path has to …
```
> Create demo/ before running ablog start

- .pre-commit-config.yaml
- docs/release/ablog-v0.11-released.rst
- src/ablog/__init__.py
Fixes https://github.com/sunpy/ablog/issues/277
> support sphinx i hope

- src/ablog/post.py
Closes #279. This PR changes the return type of `_strip` function in `blog.py` to a `list` rather than `set`. This ensures
the order of values specified in the blog (e.g. `:author:`) is maintained on the postlist.
> Make '_strip' function return as list not set.

- docs/manual/ablog-configuration-options.rst
I tried to improve readability of Ablog configuration option page. I did
- group related settings together (e.g., blog_languages and blog_default_language together,    move blog_baseurl, blog_title belong to "Feed generation")
- improve description of sidebars
- improve description of some options
> Improve ablog-configuration-options.rst
