sunpy/ablog

- ablog/__init__.py
- ablog/blog.py
- appveyor.yml
- docs/release/ablog-v0.9-released.rst
Should fix the issue. Would need AppVeyor to check tho.
> Windows Fix and AppVeyor

- ablog/templates/postcard2.html
Hi, and very thank you for ablog.
I found unclosed tag when `{% if fa %}` :)
> show </span> when if fa

- ablog/commands.py
- ablog/post.py
Hi!
When I create file contains japanese text, file encoding is changed SJIS.
So, I add encoding settings.
> Add create file encoding

- .circleci/config.yml
- README.rst
- ablog/post.py
- appveyor.yml
- setup.py
Need to figure out Appy as well, also why circle isnt theming the docs.
> change to missing_reference

- ablog/start.py
Be a bit smarter about what we're doing. In particular, fixes #34
> Fix sidebar and blog_baseurl misconfig during quick start

- ablog/templates/postnavy.html
Hi, I found a span tag is not closed on the latest post.
It seems to be caused by the closing tag is placed in if-block in postnavy.html.
Please review and approve.
Regards.
> Fix unclosed span tag

- .circleci/config.yml
- .travis.yml
- Makefile
- appveyor.yml
- setup.cfg
Supersedes #53 as I will probably also fix whatever else is broken.
> Pin werkzeug to < 1

- ablog/locale/fr/LC_MESSAGES/sphinx.po
Hello,
I've translated ablog into french. It's not perfect because, in french, "Posts in" can be "Billets dans" for categories or "Billets en" for dates (but it's not totally a problem if we consider a year as a category...). So I did only the po file, and I didn't change python files.
> Add french locale

- .circleci/config.yml
- .readthedocs.yml
- .travis.yml
- LICENSE.rst
- README.rst
- ablog/__init__.py
- ablog/blog.py
- ablog/commands.py
- ablog/post.py
- ablog/start.py
- ablog/version.py
- appveyor.yml
- docs/conf.py
- docs/index.rst
- docs/manual/cross-referencing-blog-pages.rst
- setup.cfg
Fixes https://github.com/sunpy/ablog/issues/62
Fixes https://github.com/sunpy/ablog/issues/55
> Update underlying stuff in Ablog.

- docs/manual/ablog-quick-start.rst
- docs/manual/posting-and-listing.rst
Thanks for your awesome project, it makes sphinx more powerful.
BTW, Both https://github.com/sunpy/sunpy/blob/master/CODE_OF_CONDUCT.rst and https://docs.sunpy.org/en/latest/dev_guide/newcomers.html#code in your issue template point to 404 page.
> Some minor fixes

- docs/manual/ablog-configuration-options.rst
> Add isso integration

- docs/manual/notebook_support.ipynb
> Fix typo in "extennsion"

- docs/index.rst
- docs/manual/ablog-configuration-options.rst
> docs: Use ref link rather than hardcode link

- ablog/__init__.py
- ablog/blog.py
- ablog/post.py
- ablog/start.py
- docs/manual/notebook_support.ipynb
- setup.cfg
- tests/test_build.py
Fixes https://github.com/sunpy/ablog/issues/148
> random + test fix

- ablog/blog.py
- ablog/post.py
- azure-pipelines.yml
- docs/release/ablog-v0.10-released.rst
- setup.cfg
- tox.ini
Fixes https://github.com/sunpy/ablog/issues/151
> findall -> traverse for older versions of docutils

- README.rst
- ablog/post.py
- azure-pipelines.yml
- docs/index.rst
- docs/release/ablog-v0.10-released.rst
- setup.cfg
- tox.ini
Fixes https://github.com/sunpy/ablog/issues/171
> Sort Feed posts by date 

- .djlintrc
- .pre-commit-config.yaml
- ablog/templates/ablog/postcard2.html
- ablog/templates/ablog/postnavy.html
- ablog/templates/page.html
- ablog/templates/postcard2.html
- ablog/templates/postnavy.html
- docs/release/ablog-v0.10-released.rst
- docs/release/ablog-v0.2-released.rst
- docs/release/ablog-v0.3-released.rst
- docs/release/ablog-v0.5-released.rst
- docs/release/ablog-v0.6-released.rst
- docs/release/ablog-v0.7-released.rst
- docs/release/ablog-v0.8-released.rst
- docs/release/ablog-v0.9-released.rst
- tox.ini
Stolen from a PR on pydata-theme repo
> add linter for html

- docs/conf.py
- src/ablog/templates/ablog/languages.html
- src/ablog/templates/ablog/locations.html
- src/ablog/templates/ablog/postcard.html
- src/ablog/templates/ablog/postcard2.html
- src/ablog/templates/languages.html
- src/ablog/templates/locations.html
- src/ablog/templates/postcard.html
- src/ablog/templates/postcard2.html
- tox.ini
Fixes https://github.com/sunpy/ablog/issues/186 hopefully.
> add ablog-sidebar-item to templates I missed

- .pre-commit-config.yaml
- azure-pipelines.yml
- setup.cfg
- tox.ini
Make sure we aren't too broken under sphinx6
> [0.10] CI check for Sphinx 6.0

- .gitignore
- .pre-commit-config.yaml
- setup.py
- src/ablog/post.py
- tox.ini
Fixes https://github.com/sunpy/ablog/issues/205
At least with the ablog docs I was not able to replicate that error but maybe it is time to switch up the theme to a new one.
> Add linkcheck build and check for attr

- docs/release/ablog-v0.11-released.rst
> Patch broken docbuild

- src/ablog/templates/ablog/postcard2.html
- src/ablog/templates/postcard2.html
This fixes the post issue on sunpy.org with the new theme.
Without this change you could get in a situation where you closed a div without opening it.
> Fix incorrect /div when using discuss

- .circleci/config.yml
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- ablog-conda-test-env.yml
- setup.cfg
- tox.ini
I can't use main for 0.11 due to the (re)template and the other changes that I have done.
> Release branch instead of main for 0.11

- src/ablog/templates/ablog/archives.html
- src/ablog/templates/ablog/categories.html
- src/ablog/templates/ablog/tagcloud.html
> Fix sidebars CSS naming
